name: Terraform Apply

on:
  pull_request_review:
    #branches :
    #    - 'main'
    #types: [submitted]

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update Pull Request
        uses: actions/github-script@v6
        #if: github.event.review.state == 'approved'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              text: 'Trying out GitHub actions!'
            })
